Kill existing matching processes on startup
yuvipanda/cryptnono pull request #11
Opened 2023-12-03 22:54 UTC by manics

I thought parsing `/proc/*/cmdline` was simpler than installing psutil.

I've only tested this in a VM (following https://github.com/yuvipanda/cryptnono/pull/10), not as a K8s container.

In one terminal run
```sh
sh -c 'sleep 1h; /bin/echo cryptnono.banned.string1'
```
In another run
```
sudo ./scripts/execwhacker.py --config example/config.json --debug
```

2023-12-03 22:56 UTC, manics commented
On second thoughts this probably requires mounting `/proc` into the container....

2023-12-03 23:19 UTC, manics commented
Not tested on k8s, but this seems to work on a VM: `sudo podman run -it --rm --privileged --pid=host -v /usr/src:/usr/src:ro -v /sys:/sys:ro -v /lib/modules:/lib/modules:ro -v $PWD/example:/example -v /proc:/proc:ro docker.io/manics/cryptnono:pr11 /scripts/execwhacker.py --config /example/config.json`

2023-12-03 23:28 UTC, manics commented
An alternative way (avoiding threads) is to have a second mode for execwhacker where it only does a batch kill of existing processes, then exits, or sleeps and re-runs after N minutes to catch any missed processes, running in a third container in the same pod.

2023-12-04 03:12 UTC, yuvipanda requested changes
w00t, this is awesome <3 Thanks for working on it, @manics.

Can you change this to use psutil instead? I think that'll be cleaner, and easier to reason about.

Not necessarily as part of this PR, but I think this should actually run every 10 minutes or so on the thread anyway, so we catch things that are missed by ebpf.

2023-12-04 03:13 UTC, yuvipanda commented on cryptnono/templates/daemonset.yaml
> +        - hostPath:
is this needed given we already set `hostPID: true` here?

2023-12-04 03:14 UTC, yuvipanda commented on scripts/execwhacker.py
> +                    banned_strings_automaton,
Let's pass a param here (like 'source') that tells us where this kill came from? Lets us evaluate if a *lot* of processes are escaping ebpf or just a few.

2023-12-04 21:07 UTC, manics commented on cryptnono/templates/daemonset.yaml
> +        - hostPath:
No, I've removed it

2023-12-04 21:10 UTC, manics commented on scripts/execwhacker.py
> +    with banned_strings_automaton_lock:
A queue might be more elegant, but https://github.com/WojciechMula/pyahocorasick/issues/114#issuecomment-664601322 suggests the algorithm is CPU bound, and the `check_existing_processes` thread is only active every 10 minutes, so I think a lock is good enough

2023-12-04 23:25 UTC, manics commented
I thought I might as well throw in a GH workflow test
```
Run python -mpytest -v tests/
============================= test session starts ==============================
platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0 -- /opt/hostedtoolcache/Python/3.11.6/x64/bin/python
cachedir: .pytest_cache
rootdir: /home/runner/work/cryptnono/cryptnono
collecting ... collected 3 items

tests/test_cryptnono_container.py::test_allowed PASSED                   [ 33%]
tests/test_cryptnono_container.py::test_killed PASSED                    [ 66%]
tests/test_cryptnono_container.py::test_self_changing_killed PASSED      [100%]

============================== 3 passed in 13.02s ==============================

Run docker logs cryptono
2023-12-04 23:22:50,245 Found 1 substrings to check process cmdlines for
2023-12-04 23:22:50,245 Found 1 patterns to explicitly allow
2023-12-04 23:22:50,245 Compiling and loading BPF program...
2023-12-04 23:22:53,799 Took 3.55s to startup
2023-12-04 23:22:53,799 Checking existing processes
2023-12-04 23:22:53,800 Watching for processes we don't like...
2023-12-04 23:22:53,812 Killed 0 existing processes
2023-12-04 23:23:00,809 action:spared pid:5793 cmdline:/opt/hostedtoolcache/python/3.11.6/x64/bin/python -c 'print('"'"'allowed cryptnono.banned.string1'"'"')' matched:cryptnono.banned.string1 allowed-by:.*allowed\s+cryptnono\.banned\.string1 source:execwhacker.bpf
2023-12-04 23:23:00,820 action:killed pid:5794 cmdline:/opt/hostedtoolcache/python/3.11.6/x64/bin/python -c 'print('"'"'cryptnono.banned.string1'"'"')' matched:cryptnono.banned.string1 source:execwhacker.bpf
2023-12-04 23:23:03,812 Checking existing processes
2023-12-04 23:23:03,817 Killed 0 existing processes
2023-12-04 23:23:13,817 Checking existing processes
2023-12-04 23:23:13,823 action:killed pid:5795 cmdline:cryptnono.banned.string1 no/cryptnono/tests/resources/cryptnono-test-self-changing-cmdline matched:cryptnono.banned.string1 source:psutil.process_iter
2023-12-04 23:23:13,823 Killed 1 existing processes
```

2023-12-04 23:51 UTC, yuvipanda reviewed
This is awesome! Left a couple of comments but happy to merge once those are fixed.

2023-12-04 23:51 UTC, yuvipanda commented on tests/resources/cryptnono-test-self-changing-cmdline.c
> +    snprintf(argv[0], strlen(argv[0]), "cryptnono.banned.string1");
Can you write a comment here on what this is doing?

2023-12-04 23:51 UTC, yuvipanda commented on scripts/execwhacker.py
> +def check_existing_processes(banned_strings_automaton, allowed_patterns, interval):
Add a docstring?

2023-12-04 23:51 UTC, yuvipanda commented on scripts/execwhacker.py
> +        logging.info(f"Killed {count} existing processes")
Let's keep it in the style of the other log messages, with a `source:`, `action:` etc to make long term grepping easier?

2023-12-05 18:31 UTC, manics commented
Updated!

2023-12-05 21:51 UTC, yuvipanda commented on tests/resources/cryptnono-test-self-changing-cmdline.c
> + * Afger a few seconds the executable overwrites it's argv[0] to the banned string
```suggestion
 * After a few seconds the executable overwrites it's argv[0] to the banned string
```

2023-12-05 21:52 UTC, merged

2023-12-05 21:52 UTC, yuvipanda commented
Yay, thank you @manics. Think you can deploy this?

2023-12-06 10:14 UTC, manics commented
https://github.com/yuvipanda/cryptnono/pull/12 (hopefully) means this will be automatically deployed by a mybinder.org-deploy workflow

2023-12-06 21:43 UTC, manics commented
Seems to be working!

2023-12-06 21:46 UTC, yuvipanda commented
yay, THANK YOU SO MUCH @manics

2023-12-06 21:47 UTC, yuvipanda commented
I've also invited you as a collaborator.